import { FormSchema, FormField, FormFieldOption } from './types';

export const ESTRES_SCALE_OPTIONS: FormFieldOption[] = [
  { id: 'e1', label: '1. Nunca', value: '1' },
  { id: 'e2', label: '2. Casi Nunca', value: '2' },
  { id: 'e3', label: '3. Pocas Veces', value: '3' },
  { id: 'e4', label: '4. Algunas Veces', value: '4' },
  { id: 'e5', label: '5. Relativamente Frecuente', value: '5' },
  { id: 'e6', label: '6. Muy Frecuente', value: '6' },
];

export const LIPS_SCALE_OPTIONS: FormFieldOption[] = [
  { id: 'l0', label: '0. No ha experimentado esa conducta en absoluto', value: '0' },
  { id: 'l1', label: '1. La ha experimentado un poco', value: '1' },
  { id: 'l2', label: '2. La ha experimentado moderada o medianamente', value: '2' },
  { id: 'l3', label: '3. La ha experimentado bastante', value: '3' },
  { id: 'l4', label: '4. La ha experimentado mucho o extremadamente', value: '4' },
];

const STANDARD_PUESTOS_OPTIONS: FormFieldOption[] = [
  { id: 'ep1', label: '1. DIRECCIÓN / GERENCIA', value: '1' },
  { id: 'ep2', label: '2. ADMINISTRACIÓN / FINANZAS', value: '2' },
  { id: 'ep3', label: '3. COMERCIAL / VENTAS', value: '3' },
  { id: 'ep4', label: '4. COORDINADORES / SUPERVISORES', value: '4' },
  { id: 'ep5', label: '5. OPERACIONES / PLANTA', value: '5' },
  { id: 'ep6', label: '6. LOGÍSTICA / BODEGA', value: '6' },
  { id: 'ep7', label: '7. SERVICIO TÉCNICO / MANTENIMIENTO', value: '7' },
  { id: 'ep28', label: '28. PRODUCCIÓN LÍNEA CONTINUA', value: '28' },
];

export const estresLaboralForm: FormSchema = {
  id: 'form-estres-laboral',
  code: 'estres-laboral',
  title: 'TEST DE ESTRÉS LABORAL',
  company: '',
  description: 'Permite conocer en qué grado el trabajador padece los síntomas asociados al estrés.\n\nInstrucciones:\nDe los siguientes síntomas, selecciona el grado experimentado durante los últimos 3 meses de acuerdo la escala presentada. Los síntomas deben asociarlos a situaciones causadas por el trabajo.',
  isTemplate: true,
  category: 'estres',
  createdAt: '2026-02-01T08:00:00.000Z',
  updatedAt: '2026-10-01T17:00:00.000Z',
  fields: [
    {
      id: 'sec-estres-1',
      type: 'page_break',
      label: 'Datos Demográficos y Puesto de Trabajo',
      required: false,
      order: 0,
      sectionTitle: 'Datos Demográficos y Puesto de Trabajo',
      description: 'Seleccione el cargo o agrupación de puesto a la que pertenece.',
    },
    {
      id: 'puesto',
      name: 'AGRUPACIONES DE PUESTOS',
      type: 'select',
      label: 'AGRUPACIONES DE PUESTOS',
      description: 'En los listados a continuación encuentre su cargo y seleccione según a la agrupación de la evaluación a la que pertenece.',
      required: true,
      order: 1,
      options: STANDARD_PUESTOS_OPTIONS,
    },
    {
      id: 'sec-estres-2',
      type: 'page_break',
      label: 'TEST DE ESTRÉS LABORAL',
      required: false,
      order: 2,
      sectionTitle: 'TEST DE ESTRÉS LABORAL',
      description: 'Permite conocer en qué grado el trabajador padece los síntomas asociados al estrés.\n\nInstrucciones:\nDe los siguientes síntomas, selecciona el grado experimentado durante los últimos 3 meses de acuerdo la escala presentada. Los síntomas deben asociarlos a situaciones causadas por el trabajo.',
    },
    {
      id: 'estres_q1',
      name: '1. Imposibilidad de conciliar el sueño.',
      type: 'radio',
      label: '1. Imposibilidad de conciliar el sueño.',
      required: true,
      order: 3,
      options: ESTRES_SCALE_OPTIONS,
    },
    {
      id: 'estres_q2',
      name: '2. Jaquecas y dolores de cabeza.',
      type: 'radio',
      label: '2. Jaquecas y dolores de cabeza.',
      required: true,
      order: 4,
      options: ESTRES_SCALE_OPTIONS,
    },
    {
      id: 'estres_q3',
      name: '3. Ingestiones o molestias gastrointestinales.',
      type: 'radio',
      label: '3. Ingestiones o molestias gastrointestinales.',
      required: true,
      order: 5,
      options: ESTRES_SCALE_OPTIONS,
    },
    {
      id: 'estres_q4',
      name: '4. Sensación de cansancio extremo o agotamiento.',
      type: 'radio',
      label: '4. Sensación de cansancio extremo o agotamiento.',
      required: true,
      order: 6,
      options: ESTRES_SCALE_OPTIONS,
    },
    {
      id: 'estres_q5',
      name: '5. Tendencia de comer, beber o fumar más de lo habitual.',
      type: 'radio',
      label: '5. Tendencia de comer, beber o fumar más de lo habitual.',
      required: true,
      order: 7,
      options: ESTRES_SCALE_OPTIONS,
    },
    {
      id: 'estres_q6',
      name: '6. Disminución del interés sexual.',
      type: 'radio',
      label: '6. Disminución del interés sexual.',
      required: true,
      order: 8,
      options: ESTRES_SCALE_OPTIONS,
    },
    {
      id: 'estres_q7',
      name: '7. Respiración entrecortada o sensación de ahogo.',
      type: 'radio',
      label: '7. Respiración entrecortada o sensación de ahogo.',
      required: true,
      order: 9,
      options: ESTRES_SCALE_OPTIONS,
    },
    {
      id: 'estres_q8',
      name: '8. Disminución del apetito.',
      type: 'radio',
      label: '8. Disminución del apetito.',
      required: true,
      order: 10,
      options: ESTRES_SCALE_OPTIONS,
    },
    {
      id: 'estres_q9',
      name: '9. Temblores musculares (por ejemplo, tics nerviosos o parpadeos).',
      type: 'radio',
      label: '9. Temblores musculares (por ejemplo, tics nerviosos o parpadeos).',
      required: true,
      order: 11,
      options: ESTRES_SCALE_OPTIONS,
    },
    {
      id: 'estres_q10',
      name: '10. Pinchazos o sensaciones dolorosas en distintas partes del cuerpo.',
      type: 'radio',
      label: '10. Pinchazos o sensaciones dolorosas en distintas partes del cuerpo.',
      required: true,
      order: 12,
      options: ESTRES_SCALE_OPTIONS,
    },
    {
      id: 'estres_q11',
      name: '11. Tentaciones fuertes de no levantarse por la mañana.',
      type: 'radio',
      label: '11. Tentaciones fuertes de no levantarse por la mañana.',
      required: true,
      order: 13,
      options: ESTRES_SCALE_OPTIONS,
    },
    {
      id: 'estres_q12',
      name: '12. Tendencias a sudar o palpitaciones.',
      type: 'radio',
      label: '12. Tendencias a sudar o palpitaciones.',
      required: true,
      order: 14,
      options: ESTRES_SCALE_OPTIONS,
    },
    {
      id: 'observaciones',
      name: 'Observaciones',
      type: 'textarea',
      label: 'Observaciones',
      description: 'Indique a continuación las observaciones o consideraciones que considere oportunas:',
      required: false,
      order: 15,
    },
  ],
};

export const lips60Form: FormSchema = {
  id: 'form-lips-60',
  code: 'lips-60',
  title: 'CUESTIONARIO LIPS-60. DE ESTRATEGIAS DE ACOSO EN EL TRABAJO',
  company: '',
  description: 'A continuación, hay una lista de distintas situaciones o conductas de acoso que usted puede haber sufrido en su trabajo. Marque en cada una de ellas el grado en que la ha experimentado.\n\nMarque con una equis (X):\n• El cero (“0”) si no ha experimentado esa conducta en absoluto.\n• El uno (” 1”) si la ha experimentado un poco.\n• El dos (“2”) si la ha experimentado moderada o medianamente.\n• El tres (“3”) si la ha experimentado bastante.\n• El cuatro (“4”) si la ha experimentado mucho o extremadamente:',
  isTemplate: true,
  category: 'lips60',
  createdAt: '2026-01-20T08:00:00.000Z',
  updatedAt: '2026-10-01T17:00:00.000Z',
  fields: [
    // SECCIÓN 1: DATOS DEMOGRÁFICOS
    {
      id: 'sec-lips-1',
      type: 'page_break',
      label: 'Datos Demográficos y Puesto de Trabajo',
      required: false,
      order: 0,
      sectionTitle: 'Datos Demográficos y Puesto de Trabajo',
      description: 'Seleccione el cargo o puesto de trabajo al que pertenece.',
    },
    {
      id: 'puesto',
      name: 'AGRUPACIONES DE PUESTOS',
      type: 'select',
      label: 'AGRUPACIONES DE PUESTOS',
      description: 'En los listados a continuación encuentre su cargo y seleccione según a la agrupación de la evaluación a la que pertenece.',
      required: true,
      order: 1,
      options: STANDARD_PUESTOS_OPTIONS,
    },

    // SECCIÓN 2: SUBESCALA DE DESPRESTIGIO LABORAL (DL) - 14 ítems
    {
      id: 'sec-lips-dl',
      type: 'page_break',
      label: 'SUBESCALA DE DESPRESTIGIO LABORAL (DL)',
      required: false,
      order: 2,
      sectionTitle: 'SUBESCALA DE DESPRESTIGIO LABORAL (DL)',
      description: 'Marque en cada una de las siguientes situaciones o conductas de acoso el grado en que la ha experimentado:',
    },
    {
      id: 'lips_q5',
      name: '5. Critican su trabajo.',
      type: 'radio',
      label: '5. Critican su trabajo.',
      required: true,
      order: 3,
      options: LIPS_SCALE_OPTIONS,
    },
    {
      id: 'lips_q10',
      name: '10. No le miran, o le miran con desprecio o gestos de rechazo.',
      type: 'radio',
      label: '10. No le miran, o le miran con desprecio o gestos de rechazo.',
      required: true,
      order: 4,
      options: LIPS_SCALE_OPTIONS,
    },
    {
      id: 'lips_q17',
      name: '17. Le calumnian y murmuran a sus espaldas.',
      type: 'radio',
      label: '17. Le calumnian y murmuran a sus espaldas.',
      required: true,
      order: 5,
      options: LIPS_SCALE_OPTIONS,
    },
    {
      id: 'lips_q18',
      name: '18. Hacen circular rumores falsos o infundados sobre usted.',
      type: 'radio',
      label: '18. Hacen circular rumores falsos o infundados sobre usted.',
      required: true,
      order: 6,
      options: LIPS_SCALE_OPTIONS,
    },
    {
      id: 'lips_q28',
      name: '28. Se evalúa su trabajo de manera parcial, injusta y malintencionada.',
      type: 'radio',
      label: '28. Se evalúa su trabajo de manera parcial, injusta y malintencionada.',
      required: true,
      order: 7,
      options: LIPS_SCALE_OPTIONS,
    },
    {
      id: 'lips_q49',
      name: '49. Se someten informes confidenciales y negativos sobre usted, sin notificarle ni darle oportunidad de defenderse.',
      type: 'radio',
      label: '49. Se someten informes confidenciales y negativos sobre usted, sin notificarle ni darle oportunidad de defenderse.',
      required: true,
      order: 8,
      options: LIPS_SCALE_OPTIONS,
    },
    {
      id: 'lips_q50',
      name: '50. Las personas que le apoyan reciben amenazas, o presiones para que se aparten de usted.',
      type: 'radio',
      label: '50. Las personas que le apoyan reciben amenazas, o presiones para que se aparten de usted.',
      required: true,
      order: 9,
      options: LIPS_SCALE_OPTIONS,
    },
    {
      id: 'lips_q54',
      name: '54. Callan o minimizan sus esfuerzos, logros y aciertos.',
      type: 'radio',
      label: '54. Callan o minimizan sus esfuerzos, logros y aciertos.',
      required: true,
      order: 10,
      options: LIPS_SCALE_OPTIONS,
    },
    {
      id: 'lips_q55',
      name: '55. Ocultan sus habilidades y competencias especiales.',
      type: 'radio',
      label: '55. Ocultan sus habilidades y competencias especiales.',
      required: true,
      order: 11,
      options: LIPS_SCALE_OPTIONS,
    },
    {
      id: 'lips_q56',
      name: '56. Exageran sus fallos y errores.',
      type: 'radio',
      label: '56. Exageran sus fallos y errores.',
      required: true,
      order: 12,
      options: LIPS_SCALE_OPTIONS,
    },
    {
      id: 'lips_q57',
      name: '57. Informan mal sobre su permanencia y dedicación.',
      type: 'radio',
      label: '57. Informan mal sobre su permanencia y dedicación.',
      required: true,
      order: 13,
      options: LIPS_SCALE_OPTIONS,
    },
    {
      id: 'lips_q58',
      name: '58. Controlan de manera muy estricta su horario.',
      type: 'radio',
      label: '58. Controlan de manera muy estricta su horario.',
      required: true,
      order: 14,
      options: LIPS_SCALE_OPTIONS,
    },
    {
      id: 'lips_q59',
      name: '59. Cuando solicita un permiso o actividad a la que tiene derecho se lo niegan o le ponen pegas y dificultades.',
      type: 'radio',
      label: '59. Cuando solicita un permiso o actividad a la que tiene derecho se lo niegan o le ponen pegas y dificultades.',
      required: true,
      order: 15,
      options: LIPS_SCALE_OPTIONS,
    },
    {
      id: 'lips_q60',
      name: '60. Se le provoca para obligarle a reaccionar emocionalmente.',
      type: 'radio',
      label: '60. Se le provoca para obligarle a reaccionar emocionalmente.',
      required: true,
      order: 16,
      options: LIPS_SCALE_OPTIONS,
    },

    // SECCIÓN 3: SUBESCALA DE ENTORPECIMIENTO DEL PROGRESO (EP) - 7 ítems
    {
      id: 'sec-lips-ep',
      type: 'page_break',
      label: 'SUBESCALA DE ENTORPECIMIENTO DEL PROGRESO (EP)',
      required: false,
      order: 17,
      sectionTitle: 'SUBESCALA DE ENTORPECIMIENTO DEL PROGRESO (EP)',
      description: 'Marque en cada una de las siguientes situaciones o conductas de acoso el grado en que la ha experimentado:',
    },
    {
      id: 'lips_q14',
      name: '14. Le asignan un lugar de trabajo que le mantiene aislado del resto de sus compañeros.',
      type: 'radio',
      label: '14. Le asignan un lugar de trabajo que le mantiene aislado del resto de sus compañeros.',
      required: true,
      order: 18,
      options: LIPS_SCALE_OPTIONS,
    },
    {
      id: 'lips_q27',
      name: '27. Le asignan un trabajo humillante.',
      type: 'radio',
      label: '27. Le asignan un trabajo humillante.',
      required: true,
      order: 19,
      options: LIPS_SCALE_OPTIONS,
    },
    {
      id: 'lips_q32',
      name: '32. No se le asignan nuevas tareas, no tiene nada que hacer.',
      type: 'radio',
      label: '32. No se le asignan nuevas tareas, no tiene nada que hacer.',
      required: true,
      order: 20,
      options: LIPS_SCALE_OPTIONS,
    },
    {
      id: 'lips_q33',
      name: '33. Le cortan sus iniciativas, no le permiten desarrollar sus ideas.',
      type: 'radio',
      label: '33. Le cortan sus iniciativas, no le permiten desarrollar sus ideas.',
      required: true,
      order: 21,
      options: LIPS_SCALE_OPTIONS,
    },
    {
      id: 'lips_q34',
      name: '34. Le obligan a hacer tareas absurdas o inútiles.',
      type: 'radio',
      label: '34. Le obligan a hacer tareas absurdas o inútiles.',
      required: true,
      order: 22,
      options: LIPS_SCALE_OPTIONS,
    },
    {
      id: 'lips_q35',
      name: '35. Le asignan tareas muy por debajo de su competencia.',
      type: 'radio',
      label: '35. Le asignan tareas muy por debajo de su competencia.',
      required: true,
      order: 23,
      options: LIPS_SCALE_OPTIONS,
    },
    {
      id: 'lips_q37',
      name: '37. Le obligan a realizar tareas humillantes.',
      type: 'radio',
      label: '37. Le obligan a realizar tareas humillantes.',
      required: true,
      order: 24,
      options: LIPS_SCALE_OPTIONS,
    },

    // SECCIÓN 4: SUBESCALA DE INCOMUNICACIÓN O BLOQUEO DE LA COMUNICACIÓN (BC) - 9 ítems
    {
      id: 'sec-lips-bc',
      type: 'page_break',
      label: 'SUBESCALA DE INCOMUNICACIÓN O BLOQUEO DE LA COMUNICACIÓN (BC)',
      required: false,
      order: 25,
      sectionTitle: 'SUBESCALA DE INCOMUNICACIÓN O BLOQUEO DE LA COMUNICACIÓN (BC)',
      description: 'Marque en cada una de las siguientes situaciones o conductas de acoso el grado en que la ha experimentado:',
    },
    {
      id: 'lips_q3',
      name: '3. Sus compañeros le ponen pegas para expresarse o no le dejan hablar.',
      type: 'radio',
      label: '3. Sus compañeros le ponen pegas para expresarse o no le dejan hablar.',
      required: true,
      order: 26,
      options: LIPS_SCALE_OPTIONS,
    },
    {
      id: 'lips_q11',
      name: '11. Ignoran su presencia, no responden a sus preguntas.',
      type: 'radio',
      label: '11. Ignoran su presencia, no responden a sus preguntas.',
      required: true,
      order: 27,
      options: LIPS_SCALE_OPTIONS,
    },
    {
      id: 'lips_q12',
      name: '12. La gente ha dejado o está dejando de dirigirse o de hablar con usted.',
      type: 'radio',
      label: '12. La gente ha dejado o está dejando de dirigirse o de hablar con usted.',
      required: true,
      order: 28,
      options: LIPS_SCALE_OPTIONS,
    },
    {
      id: 'lips_q13',
      name: '13. No consigue hablar con nadie, todos le evitan.',
      type: 'radio',
      label: '13. No consigue hablar con nadie, todos le evitan.',
      required: true,
      order: 29,
      options: LIPS_SCALE_OPTIONS,
    },
    {
      id: 'lips_q15',
      name: '15. Prohíben a sus compañeros que hablen con usted.',
      type: 'radio',
      label: '15. Prohíben a sus compañeros que hablen con usted.',
      required: true,
      order: 30,
      options: LIPS_SCALE_OPTIONS,
    },
    {
      id: 'lips_q16',
      name: '16. En general, se le ignora y se le trata como si fuera invisible.',
      type: 'radio',
      label: '16. En general, se le ignora y se le trata como si fuera invisible.',
      required: true,
      order: 31,
      options: LIPS_SCALE_OPTIONS,
    },
    {
      id: 'lips_q51',
      name: '51. Devuelven, abren o interceptan su correspondencia.',
      type: 'radio',
      label: '51. Devuelven, abren o interceptan su correspondencia.',
      required: true,
      order: 32,
      options: LIPS_SCALE_OPTIONS,
    },
    {
      id: 'lips_q52',
      name: '52. No le pasan las llamadas, o dicen que no está.',
      type: 'radio',
      label: '52. No le pasan las llamadas, o dicen que no está.',
      required: true,
      order: 33,
      options: LIPS_SCALE_OPTIONS,
    },
    {
      id: 'lips_q53',
      name: '53. Pierden u olvidan los encargos para usted.',
      type: 'radio',
      label: '53. Pierden u olvidan los encargos para usted.',
      required: true,
      order: 34,
      options: LIPS_SCALE_OPTIONS,
    },

    // SECCIÓN 5: SUBESCALA DE INTIMIDACIÓN ENCUBIERTA (IE) - 7 ítems
    {
      id: 'sec-lips-ie',
      type: 'page_break',
      label: 'SUBESCALA DE INTIMIDACIÓN ENCUBIERTA (IE)',
      required: false,
      order: 35,
      sectionTitle: 'SUBESCALA DE INTIMIDACIÓN ENCUBIERTA (IE)',
      description: 'Marque en cada una de las siguientes situaciones o conductas de acoso el grado en que la ha experimentado:',
    },
    {
      id: 'lips_q7',
      name: '7. Recibe llamadas telefónicas amenazantes, insultantes o acusadoras.',
      type: 'radio',
      label: '7. Recibe llamadas telefónicas amenazantes, insultantes o acusadoras.',
      required: true,
      order: 36,
      options: LIPS_SCALE_OPTIONS,
    },
    {
      id: 'lips_q9',
      name: '9. Recibe escritos y notas amenazadoras.',
      type: 'radio',
      label: '9. Recibe escritos y notas amenazadoras.',
      required: true,
      order: 37,
      options: LIPS_SCALE_OPTIONS,
    },
    {
      id: 'lips_q43',
      name: '43. Le ocasionan a propósito gastos para perjudicarle.',
      type: 'radio',
      label: '43. Le ocasionan a propósito gastos para perjudicarle.',
      required: true,
      order: 38,
      options: LIPS_SCALE_OPTIONS,
    },
    {
      id: 'lips_q44',
      name: '44. Le ocasionan daños en su domicilio o en su puesto de trabajo.',
      type: 'radio',
      label: '44. Le ocasionan daños en su domicilio o en su puesto de trabajo.',
      required: true,
      order: 39,
      options: LIPS_SCALE_OPTIONS,
    },
    {
      id: 'lips_q46',
      name: '46. Ocasionan daños en sus pertenencias o en su vehículo.',
      type: 'radio',
      label: '46. Ocasionan daños en sus pertenencias o en su vehículo.',
      required: true,
      order: 40,
      options: LIPS_SCALE_OPTIONS,
    },
    {
      id: 'lips_q47',
      name: '47. Manipulan sus herramientas (por ejemplo, borran archivos de su ordenador).',
      type: 'radio',
      label: '47. Manipulan sus herramientas (por ejemplo, borran archivos de su ordenador).',
      required: true,
      order: 41,
      options: LIPS_SCALE_OPTIONS,
    },
    {
      id: 'lips_q48',
      name: '48. Le sustraen algunas de sus pertenencias, documentos o herramientas de trabajo.',
      type: 'radio',
      label: '48. Le sustraen algunas de sus pertenencias, documentos o herramientas de trabajo.',
      required: true,
      order: 42,
      options: LIPS_SCALE_OPTIONS,
    },

    // SECCIÓN 6: SUBESCALA DE INTIMIDACIÓN MANIFIESTA (IM) - 6 ítems
    {
      id: 'sec-lips-im',
      type: 'page_break',
      label: 'SUBESCALA DE INTIMIDACIÓN MANIFIESTA (IM)',
      required: false,
      order: 43,
      sectionTitle: 'SUBESCALA DE INTIMIDACIÓN MANIFIESTA (IM)',
      description: 'Marque en cada una de las siguientes situaciones o conductas de acoso el grado en que la ha experimentado:',
    },
    {
      id: 'lips_q1',
      name: '1. Sus superiores no le dejan expresarse o decir lo que tiene que decir.',
      type: 'radio',
      label: '1. Sus superiores no le dejan expresarse o decir lo que tiene que decir.',
      required: true,
      order: 44,
      options: LIPS_SCALE_OPTIONS,
    },
    {
      id: 'lips_q2',
      name: '2. Le interrumpen cuando habla.',
      type: 'radio',
      label: '2. Le interrumpen cuando habla.',
      required: true,
      order: 45,
      options: LIPS_SCALE_OPTIONS,
    },
    {
      id: 'lips_q4',
      name: '4. Le gritan o le regañan en voz alta.',
      type: 'radio',
      label: '4. Le gritan o le regañan en voz alta.',
      required: true,
      order: 46,
      options: LIPS_SCALE_OPTIONS,
    },
    {
      id: 'lips_q8',
      name: '8. Se le amenaza verbalmente.',
      type: 'radio',
      label: '8. Se le amenaza verbalmente.',
      required: true,
      order: 47,
      options: LIPS_SCALE_OPTIONS,
    },
    {
      id: 'lips_q19',
      name: '19. Le ponen en ridículo, se burlan de usted.',
      type: 'radio',
      label: '19. Le ponen en ridículo, se burlan de usted.',
      required: true,
      order: 48,
      options: LIPS_SCALE_OPTIONS,
    },
    {
      id: 'lips_q29',
      name: '29. Sus decisiones son siempre cuestionadas o contrariadas.',
      type: 'radio',
      label: '29. Sus decisiones son siempre cuestionadas o contrariadas.',
      required: true,
      order: 49,
      options: LIPS_SCALE_OPTIONS,
    },

    // SECCIÓN 7: SUBESCALA DE DESPRESTIGIO PERSONAL (DP) - 7 ítems
    {
      id: 'sec-lips-dp',
      type: 'page_break',
      label: 'SUBESCALA DE DESPRESTIGIO PERSONAL (DP)',
      required: false,
      order: 50,
      sectionTitle: 'SUBESCALA DE DESPRESTIGIO PERSONAL (DP)',
      description: 'Marque en cada una de las siguientes situaciones o conductas de acoso el grado en que la ha experimentado:',
    },
    {
      id: 'lips_q6',
      name: '6. Critican su vida privada.',
      type: 'radio',
      label: '6. Critican su vida privada.',
      required: true,
      order: 51,
      options: LIPS_SCALE_OPTIONS,
    },
    {
      id: 'lips_q20',
      name: '20. Le tratan como si fuera un enfermo mental o lo dan a entender.',
      type: 'radio',
      label: '20. Le tratan como si fuera un enfermo mental o lo dan a entender.',
      required: true,
      order: 52,
      options: LIPS_SCALE_OPTIONS,
    },
    {
      id: 'lips_q21',
      name: '21. Intentan obligarle a que se haga un examen psiquiátrico o una evaluación psicológica.',
      type: 'radio',
      label: '21. Intentan obligarle a que se haga un examen psiquiátrico o una evaluación psicológica.',
      required: true,
      order: 53,
      options: LIPS_SCALE_OPTIONS,
    },
    {
      id: 'lips_q24',
      name: '24. Atacan o se burlan de sus convicciones políticas o de sus creencias religiosas.',
      type: 'radio',
      label: '24. Atacan o se burlan de sus convicciones políticas o de sus creencias religiosas.',
      required: true,
      order: 54,
      options: LIPS_SCALE_OPTIONS,
    },
    {
      id: 'lips_q25',
      name: '25. Ridiculizan o se burlan de su vida privada.',
      type: 'radio',
      label: '25. Ridiculizan o se burlan de su vida privada.',
      required: true,
      order: 55,
      options: LIPS_SCALE_OPTIONS,
    },
    {
      id: 'lips_q30',
      name: '30. Le dirigen insultos o comentarios obscenos o degradantes.',
      type: 'radio',
      label: '30. Le dirigen insultos o comentarios obscenos o degradantes.',
      required: true,
      order: 56,
      options: LIPS_SCALE_OPTIONS,
    },
    {
      id: 'lips_q31',
      name: '31. Le hacen avances, insinuaciones o gestos sexuales.',
      type: 'radio',
      label: '31. Le hacen avances, insinuaciones o gestos sexuales.',
      required: true,
      order: 57,
      options: LIPS_SCALE_OPTIONS,
    },

    // SECCIÓN 8: ITEMS NO AGRUPADOS EN LAS SUBESCALAS ANTERIORES - 10 ítems
    {
      id: 'sec-lips-no-agrupados',
      type: 'page_break',
      label: 'ITEMS NO AGRUPADOS EN LAS SUBESCALAS ANTERIORES',
      required: false,
      order: 58,
      sectionTitle: 'ITEMS NO AGRUPADOS EN LAS SUBESCALAS ANTERIORES',
      description: 'Marque en cada una de las siguientes situaciones o conductas de acoso el grado en que la ha experimentado:',
    },
    {
      id: 'lips_q22',
      name: '22. Se burlan de alguna deformidad o defecto físico que pueda tener.',
      type: 'radio',
      label: '22. Se burlan de alguna deformidad o defecto físico que pueda tener.',
      required: true,
      order: 59,
      options: LIPS_SCALE_OPTIONS,
    },
    {
      id: 'lips_q23',
      name: '23. Imitan su forma de andar, su voz, sus gestos para ponerle en ridículo.',
      type: 'radio',
      label: '23. Imitan su forma de andar, su voz, sus gestos para ponerle en ridículo.',
      required: true,
      order: 60,
      options: LIPS_SCALE_OPTIONS,
    },
    {
      id: 'lips_q26',
      name: '26. Se burlan de su nacionalidad, procedencia o lugar de origen.',
      type: 'radio',
      label: '26. Se burlan de su nacionalidad, procedencia o lugar de origen.',
      required: true,
      order: 61,
      options: LIPS_SCALE_OPTIONS,
    },
    {
      id: 'lips_q36',
      name: '36. Le sobrecargan sin cesar con tareas nuevas y diferentes.',
      type: 'radio',
      label: '36. Le sobrecargan sin cesar con tareas nuevas y diferentes.',
      required: true,
      order: 62,
      options: LIPS_SCALE_OPTIONS,
    },
    {
      id: 'lips_q38',
      name: '38. Le asignan tareas muy difíciles o muy por encima de su preparación, en las que es muy probable que fracase.',
      type: 'radio',
      label: '38. Le asignan tareas muy difíciles o muy por encima de su preparación, en las que es muy probable que fracase.',
      required: true,
      order: 63,
      options: LIPS_SCALE_OPTIONS,
    },
    {
      id: 'lips_q39',
      name: '39. Le obligan a realizar trabajos nocivos o peligrosos.',
      type: 'radio',
      label: '39. Le obligan a realizar trabajos nocivos o peligrosos.',
      required: true,
      order: 64,
      options: LIPS_SCALE_OPTIONS,
    },
    {
      id: 'lips_q40',
      name: '40. Le amenazan con violencia física.',
      type: 'radio',
      label: '40. Le amenazan con violencia física.',
      required: true,
      order: 65,
      options: LIPS_SCALE_OPTIONS,
    },
    {
      id: 'lips_q41',
      name: '41. Recibe ataques físicos leves, como advertencia.',
      type: 'radio',
      label: '41. Recibe ataques físicos leves, como advertencia.',
      required: true,
      order: 66,
      options: LIPS_SCALE_OPTIONS,
    },
    {
      id: 'lips_q42',
      name: '42. Le atacan físicamente sin ninguna consideración.',
      type: 'radio',
      label: '42. Le atacan físicamente sin ninguna consideración.',
      required: true,
      order: 67,
      options: LIPS_SCALE_OPTIONS,
    },
    {
      id: 'lips_q45',
      name: '45. Recibe agresiones sexuales físicas directas.',
      type: 'radio',
      label: '45. Recibe agresiones sexuales físicas directas.',
      required: true,
      order: 68,
      options: LIPS_SCALE_OPTIONS,
    },

    // OBSERVACIONES
    {
      id: 'observaciones',
      name: 'Observaciones',
      type: 'textarea',
      label: 'Observaciones',
      description: 'Indique a continuación las observaciones o consideraciones que considere oportunas:',
      required: false,
      order: 69,
    },
  ],
};
